DROP TABLE IF EXISTS `categories`;
CREATE TABLE `categories` (
  `id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `cat` varchar(50),
  `section_id` varchar(250),
  `link_text` varchar(250)
);

INSERT INTO `categories` (`id`, `cat`, `section_id`, `link_text`) VALUES
(1, 'Moral Law', 'baptism', 'BAPTISM'),
(2, 'Moral Law', 'bible', 'BIBLE'),
(3, 'Moral Law', 'ceremonial-law', 'CEREMONIAL LAW'),
(4, 'Moral Law', 'civil-government', 'CIVIL GOVERNMENT'),
(5, 'Moral Law', 'communion', 'COMMUNION'),
(6, 'Moral Law', 'disputes', 'DISPUTES'),
(7, 'Moral Law', 'earth-agriculture-animal', 'EARTH/AGRICULTURE/ANIMAL CRUELTY'),
(8, 'Moral Law', 'excommunication', 'EXCOMMUNICATION'),
(9, 'Moral Law', 'family', 'FAMILY'),
(10, 'Moral Law', 'false-religion', 'FALSE RELIGION'),
(11, 'Moral Law', 'fear', 'FEAR'),
(12, 'Moral Law', 'fornication', 'FORNICATION'),
(13, 'Moral Law', 'friends', 'FRIENDS'),
(14, 'Moral Law', 'gender', 'GENDER'),
(15, 'Moral Law', 'good-manners', 'GOOD MANNERS'),
(16, 'Moral Law', 'gratitude', 'GRATITUDE'),
(17, 'Moral Law', 'housing', 'HOUSING'),
(18, 'Moral Law', 'humility-honor', 'HUMILITY/HONOR'),
(19, 'Moral Law', 'joy', 'JOY'),
(20, 'Moral Law', 'justice-equity-civil-moral', 'JUSTICE & EQUITY (CIVIL & MORAL)'),
(21, 'Moral Law', 'love-hate', 'LOVE & HATE'),
(22, 'Moral Law', 'money', 'MONEY'),
(23, 'Moral Law', 'new-testament-church', 'NEW TESTAMENT CHURCH'),
(24, 'Moral Law', 'obeying-authority', 'OBEYING AUTHORITY'),
(25, 'Moral Law', 'patience', 'PATIENCE'),
(26, 'Moral Law', 'physical', 'PHYSICAL'),
(27, 'Moral Law', 'praise', 'PRAISE'),
(28, 'Moral Law', 'prayer', 'PRAYER'),
(29, 'Moral Law', 'prevention-of-sin', 'PREVENTION OF SIN'),
(30, 'Moral Law', 'sexual-sins', 'SEXUAL SINS'),
(31, 'Moral Law', 'strength', 'STRENGTH'),
(32, 'Moral Law', 'thoughts', 'THOUGHTS'),
(33, 'Moral Law', 'tribulation', 'TRIBULATION'),
(34, 'Moral Law', 'trust', 'TRUST'),
(35, 'Moral Law', 'vows', 'VOWS'),
(36, 'Moral Law', 'wisdom', 'WISDOM'),
(37, 'Moral Law', 'work', 'WORK'),
(38, 'Moral Law', 'zmisc', 'MISC.'),
(39, 'Civil Law', '01crimes', 'CRIMES'),
(40, 'Civil Law', '03procedures', 'PROCEDURES'),
(41, 'Civil Law', '04sabbath-years', 'SABBATH YEARS'),
(42, 'Civil Law', '05jubilee', 'JUBILEE'),
(43, 'Civil Law', '06servants', 'SERVANTS'),
(44, 'Civil Law', '07warfare', 'WARFARE'),
(45, 'Ceremonial Law', '01calendar', 'CALENDAR'),
(46, 'Ceremonial Law', '02circumcision', 'CIRCUMCISION'),
(47, 'Ceremonial Law', '03clothing', 'CLOTHING'),
(48, 'Ceremonial Law', '04clean-unclean-foods', 'CLEAN AND UNCLEAN FOODS'),
(49, 'Ceremonial Law', '05diverse-washings', 'DIVERSE WASHINGS (RITUAL UNCLEANNESS)'),
(50, 'Ceremonial Law', '06firstfruits-not-holiday', 'FIRSTFRUITS (NOT HOLIDAY)'),
(51, 'Ceremonial Law', '07immigration-citizenship', 'IMMIGRATION/CITIZENSHIP'),
(76, 'Ceremonial Law', '28misc', 'MISC.'),
(53, 'Ceremonial Law', '09jealous-husband', 'JEALOUS HUSBAND'),
(54, 'Ceremonial Law', '10offerings-sacrifices', 'OFFERINGS/SACRIFICES'),
(55, 'Ceremonial Law', '11altar-to-god', 'ALTAR TO GOD'),
(56, 'Ceremonial Law', '12tithe', 'TITHE'),
(57, 'Ceremonial Law', '13sanctify-a-house', 'SANCTIFY A HOUSE/FIELD (FOR PRIESTS POSSESSION)'),
(58, 'Ceremonial Law', '14finding-a-slain-person', 'FINDING A SLAIN PERSON'),
(59, 'Ceremonial Law', '15burnt-offering', 'BURNT OFFERING'),
(60, 'Ceremonial Law', '16vows-and-freewill-offerings', 'VOWS AND FREEWILL OFFERINGS'),
(61, 'Ceremonial Law', '17meat-and-drink-offerings', 'MEAT AND DRINK OFFERINGS'),
(62, 'Ceremonial Law', '18peace-offering-vow', 'PEACE OFFERING-VOW & THANKSGIVING'),
(63, 'Ceremonial Law', '19sin-offering', 'SIN OFFERING'),
(64, 'Ceremonial Law', '20trespass-offering', 'TRESPASS OFFERING'),
(65, 'Ceremonial Law', '21priests-levites', 'PRIESTS/LEVITES'),
(66, 'Ceremonial Law', '22red-heifer', 'RED HEIFER'),
(67, 'Ceremonial Law', '23sabbath', 'SABBATH'),
(68, 'Ceremonial Law', '24tabernacle-sanctuary', 'TABERNACLE/SANCTUARY'),
(69, 'Ceremonial Law', '25vows', 'VOWS'),
(70, 'Ceremonial Law', '26warfare-conquering-canaan', 'WARFARE (CONQUERING CANAAN)'),
(71, 'Ceremonial Law', '27remembering-history-culture', 'REMEMBERING HISTORY (CULTURE)'),
(72, 'Moral Law', 'protection-from-harm', 'PROTECTION FROM HARM'),
(73, 'Moral Law', 'rewards-in-heaven', 'REWARDS IN HEAVEN'),
(74, 'Moral Law', 'righteous-appearance', 'RIGHTEOUS APPEARANCE'),
(75, 'Moral Law', 'speech', 'SPEECH'),
(78, 'Civil Law', '02property', 'PROPERTY');

